ALTER TABLE "public"."analytics_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."app_version" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."avatars" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "avatars_select_authenticated" ON "public"."avatars" FOR SELECT USING ((( SELECT "auth"."uid"() AS "uid") IS NOT NULL));
ALTER TABLE "public"."chore_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."chores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."device_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."expense_plan_debtors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."expense_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."expense_splits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."expenses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."gratitude_wall_mentions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."gratitude_wall_personal_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."gratitude_wall_personal_reads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."gratitude_wall_posts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."gratitude_wall_reads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."home_entitlements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."home_mood_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."home_mood_feedback_counters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."home_nps" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."home_plan_limits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."home_usage_counters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."homes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."house_pulse_labels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."house_pulse_reads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."house_pulse_weekly" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."house_vibe_labels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."house_vibe_mapping_effects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."house_vibe_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."house_vibes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."invites" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."leads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."leads_rate_limits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."member_cap_join_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."memberships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."notification_preferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."notification_sends" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."outreach_event_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."outreach_rate_limits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."outreach_source_aliases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."outreach_sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."paywall_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."preference_report_acknowledgements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."preference_report_revisions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."preference_report_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."preference_reports" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."preference_responses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."preference_taxonomy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."preference_taxonomy_defs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_select_authenticated" ON "public"."profiles" FOR SELECT USING (("id" = ( SELECT "auth"."uid"() AS "uid")));
ALTER TABLE "public"."reserved_usernames" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."revenuecat_event_processing" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."revenuecat_webhook_events" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_all_outreach_aliases" ON "public"."outreach_source_aliases" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "service_role_all_outreach_rate_limits" ON "public"."outreach_rate_limits" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "service_role_all_outreach_sources" ON "public"."outreach_sources" TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "service_role_read_outreach_event_logs" ON "public"."outreach_event_logs" FOR SELECT TO "service_role" USING (true);
ALTER TABLE "public"."share_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."shared_preferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."user_subscriptions" ENABLE ROW LEVEL SECURITY;
